apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: leesy010504/ttt-static:0.0.5
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          env:
            - name: VITE_SERVER_URL
              value: "https://tictactalk.studio"
          ports:
            - containerPort: 80
