apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-service
  template:
    metadata:
      labels:
        app: voice-service
    spec:
      serviceAccountName: voice-sa
      securityContext:
        fsGroup: 2000
      containers:
        - name: voice-container
          image: leesy010504/ttt-voice:latest
          resources:
            requests:
              cpu: 300m
              memory: 1500Mi
            limits:
              cpu: 3000m
              memory: 2700Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_FAIL_FAST
              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_CONFIG
              value: "DEBUG"
            - name: SPRING_CONFIG_IMPORT
              value: "kubernetes:,kubernetes:secrets"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: "voice-config"
          envFrom:
            - secretRef:
                name: voice-secret
          ports:
            - containerPort: 8080
