apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-config
  namespace: prod
  labels:
    app: voice-service
data:
  application.yaml: |
    spring:
      config:
        activate:
          on-profile: prod
      application:
        name: voice-service

      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/voice_db
        username: voice-user
        password: ${DB_PASSWORD}

      jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
          ddl-auto: update
          show_sql: true
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    rag-service:
        url: http://rag-service.prod.svc.cluster.local:8080
        receive-url: rag-service.prod.svc.cluster.local:8080/api/v1/rag/feign/receive

    ncp:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
      bucket-name: ${NCP_BUCKET_NAME}

    clova:
      speech:
        secret-key: ${CLOVA_SPEECH_SECRET_KEY}
        invoke-url: ${CLOVA_SPEECH_INVOKE_URL}
        callback-url: ${CLOVA_SPEECH_CALLBACK_URL}
    
    feign:
      client:
        config:
          rag-service:
            connectTimeout: 5000
            readTimeout: 120000
