apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: prod
data:
  POSTGRES_DB: security_db          
  POSTGRES_USER: security_user      
  
  postgresql.conf: |                
    listen_addresses = '*'          
    max_connections = 100           
    
    shared_buffers = 256MB          
    effective_cache_size = 1GB      
    maintenance_work_mem = 64MB     
    
    wal_level = replica             
    max_wal_senders = 3             
    
    logging_collector = on          
    log_directory = 'pg_log'        
    log_statement = 'all'           
    log_duration = on               
    
  pg_hba.conf: |                  
    local   all   all               trust      
    host    all   all   0.0.0.0/0   md5       
    host    all   all   ::0/0       md5     
