apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-gateway-sa
  namespace: prod
  labels:
    app: gateway-service
    env: prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-config-reader
  namespace: prod
  labels:
    app: gateway-service
    env: prod
rules:
- apiGroups: [""] 
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-binding
  namespace: prod
  labels:
    app: gateway-service
    env: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-config-reader
subjects:
- kind: ServiceAccount
  name: spring-gateway-sa
  namespace: prod
